# Generated by Django 2.1.1 on 2018-10-15 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 21, 15, 5, 748650, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
